---
title: "Informe PVS"
author: "UIAPB"
date: "18/12/2017"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    logo: logo.png
runtime: shiny
---


```{r message=FALSE, warning=FALSE, echo=FALSE}
library(ggplot2)
library(readr)
library(dplyr)
library(lubridate)
library(tidyr)
library(flexdashboard)
library(plotly)

base<-read_delim("/home/art/shiny-server/PVS/pruevashiny.csv", ";", escape_double = FALSE, locale = locale(date_names = "es", date_format = " %d/%m/%Y"), trim_ws = TRUE)
#base<-read_delim("/media/Datos/Data_science/Mis proyectos/shiny-server/PVS/pruevashiny.csv", ";", escape_double = FALSE, locale = locale(date_names = "es", date_format = " %d/%m/%Y"), trim_ws = TRUE)

base<-base[!is.na(base$Sexo),]
base$grupo <-ifelse(base$grupo=="Control","Control", "Intervención")

nm <- (as.Date("2016-05-01")%--%max(base$Fecha_Cita__yyyymmdd_))%/%months(1)

fechas <- as.Date("2016-05-01") + 0:nm * months(1)

source("/home/art/shiny-server/funciones.R")

```

# Introduction {.sidebar}

(El informe PVS bla bla bla fdsfdasfdasfasd        sdfasdfdsafasdf
sdfsdfsdafasd     
y esto y lo otro) 


sdfsdafsdafsdafasdfsda  sdafsdafs a     
fsdfsdfsda sdfsdafsd f     

dsfsdfsdafdas



### Analizar  
```{r, echo = FALSE}
  inputPanel(checkboxGroupInput("Habitos", label = h4("Hábitos"), 
     choices = list("A1 (al menos un hábito)" = "A1", "A1 Actividad física" = "A1_AF", "A1 Dieta" = "A1_DT", 
                    "A1 Tabaco" = "A1_TB", "A2 (al menos un hábito)" = "A2", "A2 Actividad física" = "A2_AF", "A2 Dieta" = "A2_DT", 
                    "A2 Tabaco" = "A2_TB", "A4 (al menos un hábito)" = "A4", "A4 Actividad física" = "A4_AF", "A4 Dieta" = "A4_DT", 
                    "A4 Tabaco" = "A4_TB"), selected = "A1"))       
```



# Curva de progreso

## Row 1 {data-height=250}

### 
```{r echo=FALSE}

  inputPanel("Filtrar:",
  radioButtons("Sexo", "Sexo:", choices = list("Todos" = 1, "Hombres" = 2, "Mujeres" = 3), 
                   selected = 1),
  
  sliderInput("Edad", label = "Edad:",
              min = 10, max = 80, value = c(10,80)))
```

### 
```{r echo=FALSE}
     
 inputPanel("Estratificar:",
 radioButtons("Estra", "Estratos:", choices = list("Ninguno" = 1, "Sexo" = 2, "Edad" = 3, "Cupos" = 4), 
                   selected = 1))
```
  

## Gráfico  {data-height=500}
```{r echo=FALSE, fig.height=3, fig.width=3}

renderPlotly({
  
  
  bas<-filter(base, edad_consult>input$Edad[1], edad_consult<(input$Edad[2]+1))
  bas<- bas %>% filter(UAP=="ARRIGORRIAGA")
  
  if (input$Sexo == 2)  bas <- bas %>% filter(Sexo == "Hombre")
  if (input$Sexo == 3)  bas <- bas %>% filter(Sexo == "Mujer")
  
  if (input$Estra == 1) bas <- bas %>% curva_pro(fechas) %>% gather(habito, porcen, -fechas)
  if (input$Estra == 2) bas <- bas %>% split(bas$Sexo) %>% lapply(curva_pro, fechas) %>% bind_rows(.id="Sexo") %>%  
    gather(habito,porcen, -c(fechas, Sexo))
  if (input$Estra == 3) bas <- bas %>% split(bas$edad) %>% lapply(curva_pro, fechas) %>% bind_rows(.id="Edad") %>% gather(habito, porcen, -c(fechas, Edad))
  if (input$Estra == 4) bas <- bas %>% split(bas$codcup) %>% lapply(curva_pro, fechas) %>% bind_rows(.id="Cupo") %>% gather(habito, porcen, -c(fechas, Cupo))
  
  bas <- bas %>%  filter(habito %in% input$Habitos)
  
  p <- ggplot(bas)+ geom_line(aes(x=fechas, y = porcen,col = habito)) + ylab("Porcentaje")
  if (input$Estra == 2) p <- p + facet_wrap(~Sexo)
  if (input$Estra == 3) p <- p + facet_wrap(~Edad)
  if (input$Estra == 4) p <- p + facet_wrap(~Cupo)
  
  p <- ggplotly(p, height=600)
  
  print(p)
  
})

```

# Actividad

## Row 1 {data-height=250}

### 
```{r echo=FALSE}

  inputPanel("Filtrar:",
  radioButtons("Sexo2", "Sexo:", choices = list("Todos" = 1, "Hombres" = 2, "Mujeres" = 3), 
                   selected = 1),
  
  sliderInput("Edad2", label = "Edad:",
              min = 10, max = 80, value = c(10,80)))
```

### 
```{r echo=FALSE}
     
 inputPanel("Estratificar:",
 radioButtons("Estra2", "Estratos:", choices = list("Ninguno" = 1, "Sexo" = 2, "Edad" = 3, "Cupos" = 4), 
                   selected = 1))
```
  

## Gráfico  {data-height=500}
```{r echo=FALSE, fig.height=3, fig.width=3}

renderPlotly({
  
  
  bas<-filter(base, edad_consult>input$Edad2[1], edad_consult<(input$Edad2[2]+1))
  bas<- bas %>% filter(UAP=="ARRIGORRIAGA")
  
  if (input$Sexo2 == 2)  bas <- bas %>% filter(Sexo == "Hombre")
  if (input$Sexo2 == 3)  bas <- bas %>% filter(Sexo == "Mujer")
  
  if (input$Estra2 == 1) bas <- bas %>% actividad(fechas) %>% gather(habito, porcen, -fechas)
  if (input$Estra2 == 2) bas <- bas %>% split(bas$Sexo) %>% lapply(actividad, fechas) %>% bind_rows(.id="Sexo") %>%  
    gather(habito,porcen, -c(fechas, Sexo))
  if (input$Estra2 == 3) bas <- bas %>% split(bas$edad) %>% lapply(actividad, fechas) %>% bind_rows(.id="Edad") %>% gather(habito, porcen, -c(fechas, Edad))
  if (input$Estra2 == 4) bas <- bas %>% split(bas$codcup) %>% lapply(actividad, fechas) %>% bind_rows(.id="Cupo") %>% gather(habito, porcen, -c(fechas, Cupo))
  
  bas <- bas %>%  filter(habito %in% input$Habitos)
  
  p <- ggplot(bas)+ geom_line(aes(x=fechas, y = porcen,col = habito)) + ylab("N")
  if (input$Estra2 == 2) p <- p + facet_wrap(~Sexo)
  if (input$Estra2 == 3) p <- p + facet_wrap(~Edad)
  if (input$Estra2 == 4) p <- p + facet_wrap(~Cupo)
  
  p <- ggplotly(p, height=600)
  
  print(p)
  
})

```















